# This is a basic workflow to help you get started with Actions

name: clear-output-result

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run: pwd
      - run: tree -a
      - run: rm -rf result
      - run: mkdir result
      - run: tree -a
      - run: git add result
      - run: git rm github-action-run.log
      - run: git config  user.email "you@example.com"
      - run: git config  user.name "YourName"
      - run: git commit -m "clear result:`date +%Y%m%d-%H%M%S`|"
      - run: git push
      - run: echo finished

