# This is a basic workflow to help you get started with Actions

name: extract-tapermonkey-scripts

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      path:
        description: 'input zip/tar file name'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run: pwd
      - run: tree -a
      - run: echo "The input path is:[${{ inputs.path }}]"
      - run: pip install leveldb
      - run: rm -rf result
      - run: mkdir result
      - run: python py1.py "${{ inputs.path }}"
      - run: tree -a
      - run: git add result
      - run: git add github-action-run.log
      - run: git config  user.email "you@example.com"
      - run: git config  user.name "YourName"
      - run: git commit -m "upload result:`date +%Y%m%d-%H%M%S`|"
      - run: git push
      - run: echo finished

